version: '3.8'

services:
  web:
    build: .
    command: ["/bin/bash", "/app/start.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=orbis_ai_db
      - DB_USER=orbis_ai
      - DB_PASSWORD=orbis_ai_password
      - DB_HOST=db  # This is the hostname for the db service in Docker Compose
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SECRET_KEY=your_secret_key_here
      - DEBUG=True

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=orbis_ai_db
      - POSTGRES_USER=orbis_ai
      - POSTGRES_PASSWORD=orbis_ai_password
    ports:
      - "5432:5432"  # Expose the PostgreSQL port for external connections if needed 
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A orbis_ai worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=orbis_ai_db
      - DB_USER=orbis_ai
      - DB_PASSWORD=orbis_ai_password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SECRET_KEY=your_secret_key_here
      - DEBUG=True

  celery-beat:
    build: .
    command: celery -A orbis_ai beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=orbis_ai_db
      - DB_USER=orbis_ai
      - DB_PASSWORD=orbis_ai_password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SECRET_KEY=your_secret_key_here
      - DEBUG=True

volumes:
  postgres_data:
