# Generated by Django 5.1.2 on 2024-10-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('total_pool', models.DecimalField(decimal_places=6, max_digits=18)),
                ('reward_per_task', models.DecimalField(decimal_places=6, max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdc_amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('platform_token_amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('developer_fee', models.DecimalField(decimal_places=6, max_digits=18)),
                ('burn_amount', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('task_schema', models.JSONField()),
                ('creation_schema', models.JSONField()),
                ('completion_schema', models.JSONField()),
                ('review_schema', models.JSONField()),
            ],
        ),
    ]
