# Generated by Django 5.1.2 on 2024-10-18 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='campaignpool',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaigntype'),
        ),
    ]
